#!/usr/bin/env python

# A script that's basically ls but a bit cleaner
# All it should do is list available modules
# in a clean enough format to put on the wiki

# Python, again...
# We're going to copy over stuff from 'clean-ls'

import os
import sys

base_path = '/software/modules'

ignore = ['all']

dirs = os.listdir(base_path)
dirs = set(dirs)
ignore = set(ignore)

dirs = dirs.difference(ignore)
dirs = sorted(dirs)

for d in dirs:
	full_path = base_path + '/' + d
	contents = os.listdir(full_path)
	print(full_path)
	for i in contents:
		print("  {}".format(i))

