name: Build hbquota RPM package

on:
  push:
    branches:
      - master
    paths:
      - hbquota/*
  pull_request:
    branches:
      - master
    paths:
      - hbquota/*

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the RPM package
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: "hbquota/hbquota.spec"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hbquota RPM
          path: ${{ steps.rpm.outputs.rpm_dir_path }}
